### ISSUE TITLE
Needs renaming

### ISSUE THREAD

**Issue by warpech** [StarcounterFreezer/TagManager#1]
Coincidentally, there already is an app by that name in Starcounter! https://github.com/Starcounter/UsageTracker

I think that this app (UsageTracker for Google Analytics) should be renamed to Tag Manager, because it is like Google's [Tag Manager](https://www.google.com/analytics/tag-manager/). Better ideas?

**Comment by miyconst** [comment]
Actually, this app has nothing todo with the tracking itself. It injects pieces of html code, that is all. It could also be used to inject online chat plugin or whatever.

So, the name could be just CustomHtml or CustomBlock or Something like this.

**Comment by warpech** [comment]
I think that this app can include a single or more predefined tracker templates. You just provide the Google Analytics ID in setup.

Like in WordPress, there is a plugin for that, even though you could just edit the HTML in the theme's `<head>`: https://wordpress.org/plugins/googleanalytics/

We have a Custom Html app already, which is called Content

**Comment by miyconst** [comment]
What about `VisitTracker` or `VisitorTracker`? I don't like `TagManager` much, as the app will have and already has some own logic.

**Comment by warpech** [comment]
The purpose of the app is to be a wrapper for Google Analytics web analytics software, as well as other similar 3rdparty products.

It can be used for whatever Google Tag Manager is used: https://en.wikipedia.org/wiki/Google_Tag_Manager

The concept is known in marketing world as [tag management system](https://en.wikipedia.org/wiki/Tag_management_system). This is not only for visitor tracking for purpose of web analytics, but also for ad retargeting, etc.

Similar projects are discussed on [Quora](https://www.quora.com/What-are-good-alternatives-to-Google-Tag-Manager).

Notable alternatives to GTM:

- [Ensighten tag management](https://www.ensighten.com/products/tag-management/manage/)
- [Mezzobit](http://signup.mezzobit.com/free-account/)
- [Tealium enterprise tag management](http://tealium.com/what-is-tag-management/)

So I still think Tag Manager is a relevant name. Of course it has logic - relevant to tag management.

**Comment by miyconst** [comment]
Okay, then `TagManager`.

**Comment by warpech** [comment]
Renamed the repo to TagManager, the app was not renamed yet.

I am archiving the repo now anyway, so further work won't be needed
